### ISSUE TITLE
Git LFS issue

### ISSUE THREAD

**Issue by matsui528** [media-comp/2022-BackgroundMatting#7]
I received the notification from GitHub that this repository consumes lots of Git LFS space of this organization (`media-comp`).

Please don't use Git LFS in this repository. If you use Git LFS here, the space for `media-comp` is consumed.

I guess the reason is this line?
https://github.com/media-comp/2022-BackgroundMatting/blob/main/.github/workflows/main.yml#L24

Not sure what is the best option to replace this line...

**Comment by matsui528** [comment]
(Of course, there's no penalty for this. So don't worry)

**Comment by MasaTate** [comment]
@matsui528 
I'm sorry for the inconvenience.
My model weight is too heavy.

I would delete the model from the repository.

**Comment by MasaTate** [comment]
Now I deleted the model weight and removed git lfs.
Also, I changed [GitHub Actions file](https://github.com/media-comp/2022-BackgroundMatting/blob/main/.github/workflows/main.yml) to run training code that can work without pretrained weight.

**Comment by matsui528** [comment]
:+1:
